plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/lukengo/RubymineProjects/projects/Vella-nuxt/frontend/orthodox-priest-appointment/dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/home/lukengo/RubymineProjects/projects/Vella-nuxt/frontend/orthodox-priest-appointment"
command = "npm run build-only"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]